
#define EMULATION_PAGES_START_ADDRESS        0x02000

#define DATA_EE_BANKS                                                2
#define NUM_DATA_EE_PAGES                                     5
#define DATA_EE_SIZE                                                     255
#define ERASE_WRITE_CYCLE_MAX                           1000
#define NUMBER_OF_INSTRUCTION_IN_ROW         64
#define NUMBER_OF_INSTRUCTIONS_IN_PAGE      512

#define ERASE                                                                      0x14
#define PROGRAM_ROW                                                   0x04
#define PROGRAM_WORD                                                0x24
